### ISSUE TITLE
Bug Report Bar Chart

### ISSUE THREAD

**Issue by ChrisDelClea** [tvst/plost#3]
Jo @tvst ,

think i found a bug. 
What i tried is: 

```python
plost.bar_chart(
    data=datasets['stocks'],
    bar='company',
    value=['q2', 'q3'],
    direction='horizontal'
)
```

But values of q3 get stacked on top of q2 even though the 
values of q3 should be plotted as part of q2 as the value of q2 is higher.
For `vertical` it works as expected. 

Could you double check and in case fix that? 

Best regards
Chris

**Comment by ChrisDelClea** [comment]
I think I was mistaken, it it is the normal behavior that it get's sacked on top. 
Feature Request: Would it be possible to include a param such as `included=True`,
so that the value of A (lower value) is part of the value of B and not getting plotted on top? 

Ofc, I could subtract `B=B-A` myself to get the value correctly shown in the y-axis.
If I do so, however, the value of B get's reduced and the hover does show the wrong value of B.

**Comment by tvst** [comment]
Just so I understand, today Plost supports:

Unstacked:
```
|----
|======
```

Stacked:
```
|----======
```

But you'd like:
```
|≡≡≡≡=
```
...that is, you want the bars to overlap each other (possibly with some transparency, so you can understand what's happening).

Is that right?

**Comment by tvst** [comment]
Apparently Plost already supports this, with:

```
plost.bar_chart(
    data=datasets['stocks'],
    bar='company',
    value=['q2', 'q3'],
    direction='horizontal',
    stack='layered',
    opacity=0.7
)
```

**Comment by ChrisDelClea** [comment]
Even better! Thanks a lot for digging into that for me, @tvst . We could add it to the documentation tho.
I'd also like to show you what i used it for. Gotta record it first and saidly I could not share it with the whole world,
but just to show you (i mean i know you know it anyways) how awesome streamlit and plost works together.
